# Generated by Django 2.0.1 on 2018-05-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180505_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='catgory',
            field=models.CharField(choices=[('training', '培训机构'), ('personal', '个人'), ('university', '高校')], default='traning angency', max_length=20, verbose_name='机构类别'),
        ),
    ]
