# Generated by Django 2.0.1 on 2018-05-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180508_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='student_nums',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
