# Generated by Django 2.0.1 on 2018-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorg_student_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('training', '培训机构'), ('personal', '个人'), ('university', '高校')], default='traning', max_length=20, verbose_name='机构类别'),
        ),
    ]
