# Generated by Django 2.0.1 on 2018-06-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=30, verbose_name='教师年龄'),
        ),
    ]
