# Generated by Django 2.0.1 on 2018-05-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='course',
        ),
    ]
