# Generated by Django 2.0.1 on 2018-05-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='addd_time',
            new_name='add_time',
        ),
    ]
