# Generated by Django 2.0.1 on 2018-05-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180513_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='Web后端', max_length=20, verbose_name='课程类别'),
        ),
    ]
