# Generated by Django 2.0.1 on 2018-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_knowledge',
            field=models.CharField(default='', max_length=20, verbose_name='你可以学到的技能'),
        ),
        migrations.AddField(
            model_name='course',
            name='prior_knowledge',
            field=models.CharField(default='', max_length=20, verbose_name='课程须知'),
        ),
    ]
