# Generated by Django 2.0.1 on 2018-06-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180415_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=' ', max_length=30, verbose_name='邮箱'),
        ),
    ]
