# Generated by Django 2.0.1 on 2018-04-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户留言信息', 'verbose_name_plural': '用户留言信息'},
        ),
        migrations.AlterModelTable(
            name='usermessage',
            table='user_message',
        ),
    ]
